### ISSUE TITLE
How can I use it in Arduino IDE?

### ISSUE THREAD

**Issue by ziv2013** [chegewara/EspTinyUSB#1]
Hi,

Thanks a lot for you project. And I want to try it under Arduino environment.

First I install your library then copy the source code of tinyusb to the source directory.

But I still get below error message:

Documents\Arduino\libraries\EspTinyUSB-master\src/osal/osal_freertos.h:32:20: fatal error: semphr.h: No such file or directory

Could you please with a simple guide of how to use your library?

Z.t

**Comment by chegewara** [comment]
Just like every library in arduino. Download zip and add it.

**Comment by chegewara** [comment]
Since today it wont be possible to use my library without editing arduino-esp32 core code.
We can thanks to espressif.

**Comment by ziv2013** [comment]
OK， thanks. I will try.
