### ISSUE TITLE
fatal error: SdFat.h: No such file or directory

### ISSUE THREAD

**Issue by brandonpaiz** [chegewara/EspTinyUSB#105]
Hello,

I'm getting the following error when trying to build this library.

```
In file included from /root/Arduino/libraries/EspTinyUSB/src/device/msc/sdfatusb.cpp:1:
/root/Arduino/libraries/EspTinyUSB/src/sdfatusb.h:4:10: fatal error: SdFat.h: No such file or directory
 #include "SdFat.h"
```

It appears to be caused by the import from https://github.com/chegewara/EspTinyUSB/commit/567ffd764f21f803b21dc9b1122dd00b5f523d86

**Comment by chegewara** [comment]
Thanks for reporting, i reverted that PR.

**Comment by brandonpaiz** [comment]
Thanks!
