### ISSUE TITLE
Add Release 2.0.1 to PlatformIO registry

### ISSUE THREAD

**Issue by beorosz** [chegewara/EspTinyUSB#109]
Hello there,

Version 2.0.1 is not available in the PIO registry (https://registry.platformio.org/libraries/chegewara/ESP32TinyUSB). Could you please upload it?

Thank you,
Bela

**Comment by chegewara** [comment]
Should be updated soon, i forgot to update `library.properties` last time.

**Comment by beorosz** [comment]
Thank you!
