### ISSUE TITLE
how to implement readonly in msc_sd

### ISSUE THREAD

**Issue by gopalrao111** [chegewara/EspTinyUSB#132]
Hi
example device..... sd_msc is working ok , reading, writing all ok with esp32-s2 dev module, but i also needed write protection.
What will i need to modify so as to implement readonly sd_msc ?   i.e to implement write protection .... Please help me out .... Thanks....

**Comment by chegewara** [comment]
Maybe this can help
https://github.com/chegewara/esp32-usb-v2/issues/2

**Comment by gopalrao111** [comment]
thanks for prompt reply,

TU_ATTR_WEAK bool tud_msc_is_writable_cb(uint8_t lun)
is now added to mcusb.cpp and  write_protect is working .............

1. when right click, delete option is not coming
2. format of the drive is not allowed, message pop up indicating write protected
3. when paste is done, its trying to copy and after long time prompt message of write protected is coming.

Thanks again .....
