### ISSUE TITLE
Remote pendrive code not working on ESp32 s3

### ISSUE THREAD

**Issue by micromagine** [chegewara/EspTinyUSB#152]
examples/host/remote_pendrive
i tried this code on esp32 s3 compiled ok but when insert pendrive to esp32s3 device get reset

my errors are
ELF file SHA256: 0cf01760fb528cb7

**Comment by micromagine** [comment]
ELF file SHA256: 0cf01760fb528cb7

Rebooting...
��ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)

**Comment by micromagine** [comment]
![image](https://github.com/chegewara/EspTinyUSB/assets/77408079/d369e001-4d83-4783-9243-0c6fd9c9c68e)

**Comment by chegewara** [comment]
I dont see what is not working here.
What are those files from in your logs?

It looks like a bug in your code.

**Comment by micromagine** [comment]
when i insert pendrive it reset continues other wise it works !! my task is i want to take data log in pendrive !! so m i doing anything wrong or pendrive is formatted in FAT. is it wrong !!! do you have any detail documentation or video for this code !!!

**Comment by micromagine** [comment]
I am eagerly anticipating your response! I am somewhat uncertain about the capability of connecting a pendrive to the ESP32-S3 and performing read and write operations for data logs. Your code suggests that this is achievable, and I would greatly appreciate your assistance in clarifying this matter.

**Comment by micromagine** [comment]
hello sir

**Comment by chegewara** [comment]
https://github.com/espressif/esp-usb/tree/master/host/class

**Comment by micromagine** [comment]
thank you it works!!!!

**Comment by micromagine** [comment]
https://github.com/nathalislight/esp32s3_USB_Drive/tree/main

similar code for Arduino Esp32-s3 USB HOST MSC is available .
you can update your code !!! thanx for help 
i am posting this because i am searching from this last one year now i get solution !!! thanx to https://github.com/nathalislight/
