### ISSUE TITLE
How to expose on-board external Flash as USB Mass Storage？

### ISSUE THREAD

**Issue by HelloDB** [chegewara/EspTinyUSB#19]
Thank you for your library, how to expose the onboard external flash memory as USB Mass Storage?

**Comment by chegewara** [comment]
There is no API for that, and all depends what partition would you like to expose. I think the easiest would be to expose FFat, but anyway you need to add some functions or try to use esp-idf.
In this repository is very simple and not production ready implementation to expose OTA partiton, which allows to update with drag n drop:
https://github.com/chegewara/esp32s2-msc-ota

**Comment by chegewara** [comment]
https://github.com/chegewara/EspTinyUSB/issues/50
