### ISSUE TITLE
all_in_one example in crash loop immediately after download

### ISSUE THREAD

**Issue by haverdude** [chegewara/EspTinyUSB#2]
This issue is in reference to the "all_in_one" example - I have not tried any of the others.

The code is compiling, I have the ESP32S2 branch installed (manually) in the Arduino IDE, I can build and download the code, but all it does is what is shown in the log below.

Is there any particular setup option and / or partition scheme I have to use to make this work?

> 01:00:56.909 -> ELF file SHA256: 0000000000000000
01:00:56.909 -> 
01:00:56.909 -> Rebooting...
01:00:56.909 -> ESP-ROM:esp32s2-rc4-20191025
01:00:56.943 -> Build:Oct 25 2019
01:00:56.943 -> rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
01:00:56.943 -> Saved PC:0x40025c41
01:00:56.943 -> SPIWP:0xee
01:00:56.943 -> mode:DIO, clock div:1
01:00:56.943 -> load:0x3ffe8100,len:0x4
01:00:56.943 -> load:0x3ffe8104,len:0x570
01:00:56.943 -> load:0x40050000,len:0x1620
01:00:56.943 -> load:0x40054000,len:0x1a04
01:00:56.943 -> entry 0x40050280
01:00:57.078 -> Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled.
01:00:57.078 -> 
01:00:57.078 -> Core  0 register dump:
01:00:57.078 -> PC      : 0x4001abc8  PS      : 0x00060030  A0      : 0x80080ee1  A1      : 0x3ffc8b50  
01:00:57.112 -> A2      : 0x00000000  A3      : 0x3ffbda30  A4      : 0x00001400  A5      : 0x00000000  
01:00:57.112 -> A6      : 0x4d903ceb  A7      : 0x534f4453  A8      : 0x3ffbee30  A9      : 0x3ffc8b20  
01:00:57.112 -> A10     : 0x00000000  A11     : 0x00000400  A12     : 0x00000000  A13     : 0x00000003  
01:00:57.112 -> A14     : 0x3ffc2790  A15     : 0x3ffc8c00  SAR     : 0x00000000  EXCCAUSE: 0x0000001d  
01:00:57.112 -> EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000003  LCOUNT  : 0x40026961  
01:00:57.146 -> 
01:00:57.146 -> Backtrace:0x4001abc5:0x3ffc8b50 |<-CORRUPTED

**Comment by nikthefix** [comment]
I had the same error and it was caused by the MSC example component trying to use the psram of the wrover module. Just enable PSRAM in the Tools menu.
