### ISSUE TITLE
class fs::SDFS has no member named 'readRAW'

### ISSUE THREAD

**Issue by arjuna-dev** [chegewara/EspTinyUSB#27]
Whenever I try to run any of the examples I get the following errors:

EspTinyUSB-master/src/classes/msc/sdcard.cpp:66:12: error: 'class fs::SDFS' has no member named 'readRAW'
         SD.readRAW((uint8_t*)buffer, lba);

And then a similar one but for 'writeRAW'

**Comment by chegewara** [comment]
Sorry for that. I merged SD card class before this PR has been merged:
https://github.com/espressif/arduino-esp32/pull/4777

If you dont need sd card example then you can just delete sdcard class, or you can try to modify arduino SD library.

**Comment by chegewara** [comment]
The PR has been merged to arduino-esp32 master branch now.
