### ISSUE TITLE
error: conflicting declaration of 'bool tud_vendor_control_xfer_cb(uint8_t, uint8_t, const tusb_control_request_t*)' with 'C' linkage

### ISSUE THREAD

**Issue by Yecgaa1** [chegewara/EspTinyUSB#38]
![image](https://user-images.githubusercontent.com/38446391/121785217-10877d00-cbeb-11eb-9d62-75d887deb3bf.png)

**Comment by chegewara** [comment]
Some API in tinyusb and thus in arduino-esp32 changed, but i didnt update this library yet for some other reasons. Thanks for reporting.
