### ISSUE TITLE
How to Setup the library ?

### ISSUE THREAD

**Issue by conde2** [chegewara/EspTinyUSB#4]
Hello, I'm trying to include this library to my Arduino IDE, without success.

![Captura de tela de 2020-09-21 12-24-30](https://user-images.githubusercontent.com/2137569/93786256-78cda300-fc05-11ea-8fae-a0c312a84b5c.png)

So I tried download the TinyUSB (https://github.com/hathach/tinyusb) and merge the src folder, but still getting erros.

Could you teach me the steps to make it work ?

**Comment by lucadentella** [comment]
Hi!

don't know if you have already solved... anyway you have to use the "esp32s2" branch of arduino-esp32 with this library. You cannot install it using board manager, do as it follows:

(I assume you're on Windows):
https://github.com/espressif/arduino-esp32/blob/esp32s2/docs/arduino-ide/windows.md

remember to switch to the esp32s2 branch before running get.exe 

I was able to run the examples following this procedure.
