### ISSUE TITLE
Missing usbd.h file

### ISSUE THREAD

**Issue by techniks** [chegewara/EspTinyUSB#5]
I had this working great in July or so.
I went back to revisit it and won't compile (Webusb example) due to usbd.h file missing.
Also errors related to usb endpoints.
Any help is appreciated.
Thanks!

**Comment by jivido** [comment]
Hi,
See https://github.com/chegewara/EspTinyUSB/pull/3
I had the same problem, but with the changes from that pull request the example compiles.
