### ISSUE TITLE
usb/usb_host.h: No such file or directory

### ISSUE THREAD

**Issue by Stefankante** [chegewara/EspTinyUSB#54]
Hi! 
I have try to test usb host function on new esp32-s2 but the compile failed pointed toward "usb/usb_host.h: No such file or directory"
Where I could find that file? 

Thanks

**Comment by Stefankante** [comment]
> The question is what arduino-esp32 are you using? Its been tested with `idf-master` branch, but that branch recently has been merged into master, so you have to use `master` branch. It wont work with any version released in boards manager yet.

I used Arduino ESP-32 version 2.0.0 which support ESP32-S2. 
https://github.com/espressif/arduino-esp32

**Comment by chegewara** [comment]
Master:
https://github.com/espressif/arduino-esp32
v2.0.0:
https://github.com/espressif/arduino-esp32/tree/2.0.0

You cant use master if you install with boards manager, you have to install arduino-esp32 manually.  There should be instruction how to do it.
