### ISSUE TITLE
We hope to provide an updated version based on the official USB host example

### ISSUE THREAD

**Issue by yangminglong** [chegewara/EspTinyUSB#66]
We hope to provide an updated version based on the official USB host example

[https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/cdc](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/cdc)

**Comment by chegewara** [comment]
Hi,
i dont think i will change the USB host CDC in this library:
1. it is working and its working good, i think
2. the code from your link is master, which means its part of esp-idf v5.0, and arduino-esp32 is based on v4.4, so its not going to be available any time soon
3. when it will be available in arduino, anyone can use this API and example code as is, and i am guessing it will be part of library provided by espressif in arduino-esp32 too
