### ISSUE TITLE
possible to use without Arduino?

### ISSUE THREAD

**Issue by ultrapalace** [chegewara/EspTinyUSB#79]
Hi,
I am hoping to add usb midi to my esp32s2 project.
I am working in esp-idf, and don't have Arduino installed
Is there any way that this lib can work in esp-idf?
thank you!

**Comment by chegewara** [comment]
Nope, sorry. 
You have to use plain tinyusb.
https://github.com/hathach/tinyusb/tree/master/examples/device/midi_test
