### ISSUE TITLE
[question] refactor functions to return bool when possible

### ISSUE THREAD

**Issue by chegewara** [chegewara/EspTinyUSB#8]
I am thinking about refactoring some functions to return bool value to signal if function succeeded or not, for example hid functions.

Any thoughts?

**Comment by blackketter** [comment]
That seems reasonable, assuming there's a way to determine why it failed.  What about returning an error code?

**Comment by chegewara** [comment]
There is no way to return error code, tinyusb returns bool value.

**Comment by chegewara** [comment]
Done.
