### ISSUE TITLE
Is there any plan to do usb Audio equipment

### ISSUE THREAD

**Issue by LiTongXue98** [chegewara/EspTinyUSB#86]
Recently I wanted to make a device about USB Audio, but I found that the synchronous transfer of ESP32S2 and ESP32S2 was problematic. Someone found the same problem as mine in another project. Have you ever had a similar problem before  [](https://github.com/hathach/tinyusb/issues/1382)

**Comment by chegewara** [comment]
No, there is no plan to add any more drivers so far. And no, i didnt have any problems, but except making this library i didnt work too much with USB yet.

**Comment by LiTongXue98** [comment]
好的
