### ISSUE TITLE
can not updload demo to esp32-s2

### ISSUE THREAD

**Issue by BruceAKABear** [chegewara/EspTinyUSB#89]
hi
when I upload demo to esp32-s2 ,the arduino ide syas :
`libraries\EspTinyUSB\src/usb_device.hpp:3:10: fatal error: usb/usb_host.h: No such file or directory`

how can I use this lib correctly？

my esp32 lib is v2.0.0

**Comment by touchgadget** [comment]
The latest stable version is 2.0.2.

**Comment by chegewara** [comment]
Maybe that slash makes a difference on your OS?
> usb/usb_host.h

VS
> usb\usb_host.h

**Comment by BruceAKABear** [comment]
thx,may be I should update the esp32 lib version, by the way ,my os is windows10
